# Generated by Django 5.0.6 on 2024-06-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
