# Generated by Django 5.0.6 on 2024-06-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isOpen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
